name: Send FCM Notifications

on:
  repository_dispatch:
    types: [send-ping]

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'   # enables npm caching automatically
        
    - name: Install dependencies
      run: |
        if [ ! -f package.json ]; then
          echo '{"name":"fcm-script","version":"1.0.0","dependencies":{"firebase-admin":"latest"}}' > package.json
        fi
        npm install
        
    - name: Send FCM Notifications
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        FCM_TOKENS: ${{ toJson(github.event.client_payload.tokens) }}
        NOTIFICATION_TITLE: ${{ github.event.client_payload.title }}
        NOTIFICATION_BODY: ${{ github.event.client_payload.body }}
      run: node send-fcm.js
      
    - name: Log completion
      run: |
        echo "Notification job completed at $(date)"
        echo "Tokens processed: $(echo '${{ toJson(github.event.client_payload.tokens) }}' | jq length)"
